"""
Django settings for fslearn_main project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from dotenv import load_dotenv

load_dotenv() # IF YOU FORGOT THIS, NOTHING WORKS

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-902t&hqz#-&_$#r=4+%@lb!6aaj_(*jvxtrgp85bxla48_ebrk"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('ENVIRONMENT') == 'development'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com']

# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Custom apps
    "core",
    "student",
    "teacher",
    "learning",
    "cloudinary",
    "crispy_forms",
    "crispy_bootstrap5",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.ActiveUserMiddleware",
]

ROOT_URLCONF = "fslearn_main.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "fslearn_main.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# --- DATABASE & STORAGE CONFIGURATION ---
if os.environ.get('ENVIRONMENT') == 'production':
    # LIVE: Use Neon Cloud DB and Cloudinary Storage
    DATABASES = {
        'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
    }
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage", # <-- THIS IS THE FIX
        },
    }
else:
    # LOCAL: Use Local fslearnDB and Local /media/ folder
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "fslearnDB",
            "USER": "fslearnadmin",
            "PASSWORD": "Password123!",
            "HOST": "localhost",
            "PORT": "5432",
        }
    }
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# 2. Where Django collects all static files for production (Do NOT put your dev files here)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 3. (Optional but recommended) If you ever want a global static folder outside of your apps
STATICFILES_DIRS = [
    BASE_DIR / 'static', 
]

# Add this to the very bottom of your settings.py

UNFOLD = {
    "SITE_TITLE": "FSLearn Admin",
    "SITE_HEADER": "FSLearn Dashboard",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "Curriculum & Content",
                "separator": True,
                "items": [
                    {"title": "Themes & Sections", "icon": "menu_book", "link": "/admin/learning/theme/"},
                    {"title": "Vocabulary (Words)", "icon": "spellcheck", "link": "/admin/learning/word/"},
                    {"title": "Stories", "icon": "video_library", "link": "/admin/learning/story/"},
                    {"title": "Sentence Quizzes", "icon": "format_list_numbered", "link": "/admin/learning/sentencequiz/"},
                ],
            },
            {
                "title": "Students & Progress",
                "separator": True,
                "items": [
                    {"title": "Student Profiles", "icon": "face", "link": "/admin/student/studentprofile/"},
                    {"title": "Word Progress", "icon": "trending_up", "link": "/admin/student/wordprogress/"},
                    {"title": "Story Quiz Progress", "icon": "check_circle", "link": "/admin/student/storyquizprogress/"},
                    {"title": "Quiz Progress", "icon": "assessment", "link": "/admin/student/quizprogress/"},
                ],
            },
            {
                "title": "Teachers & Staff",
                "separator": True,
                "items": [
                    {"title": "Teacher Profiles", "icon": "school", "link": "/admin/teacher/teacherprofile/"},
                    {"title": "System Users", "icon": "manage_accounts", "link": "/admin/auth/user/"},
                    {"title": "System Groups", "icon": "group", "link": "/admin/auth/group/"},
                ],
            },
            {
                "title": "FSL Media Library",
                "separator": True,
                "items": [
                    {"title": "FSL Signs", "icon": "sign_language", "link": "/admin/student/fslsign/"},
                    {"title": "FSL Words", "icon": "language", "link": "/admin/student/fslword/"},
                ],
            },
        ],
    },
}

# --- CLOUDINARY MEDIA STORAGE ---
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dedrisaul',
    'API_KEY': '233719653582825',
    'API_SECRET': 'FQA0vhml9-kJrgO3WytxaL2LK-8',
}


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"