# Generated by Django 6.0 on 2026-02-23 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(help_text='Video of the teacher asking the question', upload_to='stories/quiz_videos/')),
                ('text', models.CharField(help_text='Text version of the question (optional)', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceQuiz',
            fields=[
                ('sentencequiz_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_text', models.CharField(max_length=255)),
                ('structure_json', models.JSONField(help_text='Stores the Time, Topic, Comment breakdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(help_text='The main story video', upload_to='stories/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='stories/thumbnails/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="e.g., 'Theme 1: Knowing Who We Are'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description of this theme.')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='themes/icons/')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('choice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(help_text='The answer text displayed on the tile', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Optional image for the choice', null=True, upload_to='stories/choices/')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning.quizquestion')),
            ],
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.story'),
        ),
        migrations.AddField(
            model_name='story',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='learning.theme'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="e.g., 'Basic Identity', 'Emotions'", max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learning.theme')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'MASAYA (Happy)'", max_length=100)),
                ('slug', models.SlugField(blank=True, help_text="Auto-generated from Name (e.g., 'masaya-happy')", unique=True)),
                ('video', models.FileField(help_text='Upload the MP4 sign language clip here', upload_to='words/videos/')),
                ('image', models.ImageField(help_text='Upload the illustration/drawing here', upload_to='words/images/')),
                ('description', models.TextField(help_text="Instructions: e.g., 'Smile with both hands moving up...'")),
                ('order', models.PositiveIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='learning.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
