# Generated by Django 6.0 on 2026-01-29 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Theme 1: Knowing Who We Are'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description of this theme.')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='themes/icons/')),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Basic Identity', 'Emotions'", max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learning.theme')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'MASAYA (Happy)'", max_length=100)),
                ('slug', models.SlugField(blank=True, help_text="Auto-generated from Name (e.g., 'masaya-happy')", unique=True)),
                ('video', models.FileField(help_text='Upload the MP4 sign language clip here', upload_to='words/videos/')),
                ('image', models.ImageField(help_text='Upload the illustration/drawing here', upload_to='words/images/')),
                ('description', models.TextField(help_text="Instructions: e.g., 'Smile with both hands moving up...'")),
                ('order', models.PositiveIntegerField(default=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='learning.section')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
