# Generated by Django 6.0 on 2026-03-30 05:43

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='video',
            field=models.FileField(help_text='Video of the teacher asking the question', storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='stories/quiz_videos/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='video',
            field=models.FileField(help_text='The main story video', storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='stories/videos/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.FileField(help_text='Upload the MP4 sign language clip here', storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='words/videos/'),
        ),
    ]
