# Generated by Django 6.0 on 2026-02-13 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Video of the teacher asking the question', upload_to='stories/quiz_videos/')),
                ('text', models.CharField(help_text='Text version of the question (optional)', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The answer text displayed on the tile', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Optional image for the choice', null=True, upload_to='stories/choices/')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='learning.quizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(help_text='The main story video', upload_to='stories/videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='stories/thumbnails/')),
                ('description', models.TextField(blank=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='learning.theme')),
            ],
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.story'),
        ),
    ]
