# Generated by Django 6.0 on 2026-03-30 06:26

import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_quizquestion_video_alter_story_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='video',
            field=models.FileField(help_text='Video of the teacher asking the question', storage=learning.models.get_video_storage, upload_to='stories/quiz_videos/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='video',
            field=models.FileField(help_text='The main story video', storage=learning.models.get_video_storage, upload_to='stories/videos/'),
        ),
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.FileField(help_text='Upload the MP4 sign language clip here', storage=learning.models.get_video_storage, upload_to='words/videos/'),
        ),
    ]
