# Generated by Django 6.0 on 2026-04-09 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_quizquestion_video_alter_story_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabQuiz',
            fields=[
                ('vocabquiz_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('passing_score', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_quizzes', to='learning.section')),
            ],
        ),
    ]
