# Generated by Django 6.0 on 2026-02-23 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FSLSign',
            fields=[
                ('fslsign_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('char', models.CharField(help_text="The letter or number (e.g., 'A', '1')", max_length=5, unique=True)),
                ('media_file', models.FileField(help_text='Upload the hand sign clip here', upload_to='fsl_clips/')),
            ],
        ),
        migrations.CreateModel(
            name='FSLWord',
            fields=[
                ('fslword_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(help_text="e.g. 'EAT', 'APPLE'", max_length=100, unique=True)),
                ('video', models.FileField(help_text='Upload word video here', upload_to='fsl_words/')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('studentprofile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(help_text="What the kid wants to be called (e.g. 'King Joe')", max_length=50)),
                ('level', models.CharField(choices=[('Nursery', 'Nursery'), ('Kinder 1', 'Kinder 1'), ('Kinder 2', 'Kinder 2'), ('Prep', 'Preparatory')], default='Kinder 1', max_length=20)),
                ('section', models.CharField(help_text="e.g. 'Blueberry Class' or 'Morning Session'", max_length=20)),
                ('guardian_name', models.CharField(help_text='Parent/Guardian Name', max_length=100)),
                ('avatar', models.ImageField(default='default_avatar.png', upload_to='student_avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
