# Generated by Django 6.0 on 2025-12-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FSLSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(help_text="The letter or number (e.g., 'A', '1')", max_length=1, unique=True)),
                ('media_file', models.FileField(help_text='Upload the hand sign clip here', upload_to='fsl_clips/')),
            ],
        ),
    ]
