# Generated by Django 6.0 on 2025-12-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fslsign',
            name='char',
            field=models.CharField(help_text="The letter or number (e.g., 'A', '1')", max_length=5, unique=True),
        ),
    ]
