# Generated by Django 6.0 on 2026-02-26 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('student', '0002_quizprogress_wordprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryQuizProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, help_text='Number of questions answered correctly')),
                ('is_passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.story')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_quiz_scores', to='student.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'story')},
            },
        ),
    ]
