# Generated by Django 6.0 on 2025-12-20 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_fslsign_char'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text="What the kid wants to be called (e.g. 'King Joe')", max_length=50)),
                ('level', models.CharField(choices=[('Nursery', 'Nursery'), ('Kinder 1', 'Kinder 1'), ('Kinder 2', 'Kinder 2'), ('Prep', 'Preparatory')], default='Kinder 1', max_length=20)),
                ('section', models.CharField(help_text="e.g. 'Blueberry Class' or 'Morning Session'", max_length=20)),
                ('guardian_name', models.CharField(help_text='Parent/Guardian Name', max_length=100)),
                ('avatar', models.ImageField(default='default_avatar.png', upload_to='student_avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
