# Generated by Django 6.0 on 2026-03-30 05:43

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_storyquizprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fslsign',
            name='media_file',
            field=models.FileField(help_text='Upload the hand sign clip here', storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='fsl_clips/'),
        ),
        migrations.AlterField(
            model_name='fslword',
            name='video',
            field=models.FileField(help_text='Upload word video here', storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='fsl_words/'),
        ),
    ]
