# Generated by Django 6.0 on 2026-02-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FSLWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text="e.g. 'EAT', 'APPLE'", max_length=100, unique=True)),
                ('video', models.FileField(help_text='Upload word video here', upload_to='fsl_words/')),
            ],
        ),
    ]
