# Generated by Django 6.0 on 2026-03-30 06:26

import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_fslsign_media_file_alter_fslword_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fslsign',
            name='media_file',
            field=models.FileField(help_text='Upload the hand sign clip here', storage=student.models.get_video_storage, upload_to='fsl_clips/'),
        ),
        migrations.AlterField(
            model_name='fslword',
            name='video',
            field=models.FileField(help_text='Upload word video here', storage=student.models.get_video_storage, upload_to='fsl_words/'),
        ),
    ]
