# Generated by Django 6.0 on 2026-04-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_fslsign_media_file_alter_fslword_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
