# Generated by Django 6.0 on 2026-04-09 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_vocabquiz'),
        ('student', '0006_studentprofile_last_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabQuizProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_quiz_scores', to='student.studentprofile')),
                ('vocab_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.vocabquiz')),
            ],
            options={
                'unique_together': {('student', 'vocab_quiz')},
            },
        ),
    ]
