# Generated by Django 6.0 on 2026-04-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_vocabquizprogress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storyquizprogress',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vocabquizprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizprogress',
            name='details',
            field=models.JSONField(blank=True, help_text='Stored incorrect sequences', null=True),
        ),
        migrations.AddField(
            model_name='storyquizprogress',
            name='details',
            field=models.JSONField(blank=True, help_text='Questions answered incorrectly', null=True),
        ),
        migrations.AddField(
            model_name='vocabquizprogress',
            name='details',
            field=models.JSONField(blank=True, help_text='Words answered incorrectly', null=True),
        ),
    ]
